### ISSUE TITLE
Add disableInteractivity flag for widgets

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/airship#284]
It would be nice to have an option in the widgets to disable interactivity. This should consist of disabling pointer events and hiding the footer.

This is the CSS I'm using for the workaround:

```css
.widget {
  pointer-events: none;
  footer {
    display: none ;
  }
}
```
