### ISSUE TITLE
Set min-height for dropdown control

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/airship#433]
### Context

https://carto.com/developers/airship/examples/#example-as-dropdown

### Steps to Reproduce

1. Create an empty dropdown with default-text=""

### Current Result

![selection_357](https://user-images.githubusercontent.com/2227572/47368014-274acf80-d6e1-11e8-83e2-2e8b817e8c24.png)

### Expected result

![selection_358](https://user-images.githubusercontent.com/2227572/47368019-29ad2980-d6e1-11e8-9183-33bbeec57968.png)

```css
as-dropdown .as-dropdown__control {
  min-height: 36px;
}
```
